resources:
  - name: repo_bindu
    type: GitRepo
    configuration:
      gitProvider: bindu_github
      path: bindushree16/Rhel7_test 
      
pipelines:
  - name: jfrog_rhel_pipeline
    steps:
      - name: rehl7_test1
        type: Bash
        configuration: 
          priority: 0
          timeoutSeconds: 50000
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: aws_keys  
          inputResources:
            - name: repo_bindu
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute:
            - pwd
            - terraform --version
            - printenv
            - pushd $res_repo_bindu_resourcePath
            - terraform init            
            - ls -la
            - PWD=$(pwd)
            - echo PWD=$PWD
            - replace_envs $PWD/keys.tfvar
            - terraform apply -auto-approve -var-file="$PWD/keys.tfvar"
            - terraform output bindu_ip
            - bindu_ip_address=$(terraform output bindu_ip)
            - echo "$bindu_ip_address"
            - add_pipeline_variables bindu_ip_address=$bindu_ip_address
            - add_pipeline_files $PWD/terraform.tfstate jfrog_pipeline
            - popd

      - name: rhel7_test2
        type: Bash
        configuration:
          timeoutSeconds: 50000
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: bindu_pem 
            - name: ART_keys
            - name: art  
          inputSteps:
            - name: rehl7_test1
          inputResources:
            - name: repo_bindu   
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute:
            - printenv
            - pushd $res_repo_bindu_resourcePath
            - PWD=$(pwd)
            - echo $PWD
            - replace_envs $PWD/pipeline_installer.sh
            - cat $PWD/pipeline_installer.sh
            - echo "$int_bindu_pem_key" > bindu.pem
            - cat $PWD/bindu.pem
            - echo $bindu_ip_address
            - chmod 777 "$PWD"/pipeline_installer.sh
            - chmod 777 "$PWD"/test.sh
            - sudo chmod 600 "$PWD"/bindu.pem
            - cp "$PWD"/bindu.pem ~/.ssh/
            - cat ~/.ssh/bindu.pem
            - which ssh
            - scp -i ~/.ssh/bindu.pem $PWD/pipeline_installer.sh test.sh ec2-user@$bindu_ip_address:~
            - ssh -i ~/.ssh/bindu.pem ec2-user@$bindu_ip_address ls
            - ssh -i ~/.ssh/bindu.pem ec2-user@$bindu_ip_address "sudo ./pipeline_installer.sh"
            - ssh -i ~/.ssh/bindu.pem ec2-user@$bindu_ip_address "sudo ./test.sh"
            
      - name: rhel7_test3
        type: Bash
        configuration: 
          priority: 0
          timeoutSeconds: 50000
          environmentVariables:
            env1: value1
            env2: value2
          integrations:
            - name: aws_keys
          inputSteps:
            - name: rhel7_test2
          inputResources:
            - name: repo_bindu
          runtime:       
            type: image     #<image/host>
            image:
              custom:
                name: drydock/u16
                tag: master
        execution:
          onExecute:  
            - pushd $res_repo_bindu_resourcePath
            - echo $PWD
            - echo "$bindu_ip_address"
            - terraform init
            - replace_envs $PWD/keys.tfvar
            - restore_pipeline_files jfrog_rhel_pipeline $PWD/terraform.tfstate
            - terraform destroy -auto-approve -var-file="$PWD/keys.tfvar"
            - popd
            
            

